Algoritmo "media_idades"

Var

   , y : inteiro

Inicio

   escreval("digite dois números:")
   leia(x)
   leia(y)
   
   enquanto x <> y faca
   
      se x > y entao
         escreval("Descrescente!")
      senao
         escreval("Crescente!")
      fimse
      
      escreval("Digite outros dois numeros:")
      leia(x)
      leia(y)
      
   fimenquanto

Fimalgoritmo